export const products = [
  {
    id: 1,
    name: "Black Track Pant",
    category: "Pant",
    subcategory: "Track Pants",
    price: 1299,
    mrp: 1799,
    discount: "28% OFF",
    image: "sf_pant.png",
    images: ["sf_pant.png", "sf_pant.png", "sf_pant.png"],
    description: "Premium quality track pants designed for ultimate comfort and flexibility. Made from breathable, moisture-wicking fabric perfect for workouts or casual lounging.",
    isNewArrival: true,
    salesCount: 150,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 2,
    name: "Soul Fit Oversized Tee",
    category: "T-shirt",
    subcategory: "Normal Cotton T-Shirts",
    price: 1199,
    mrp: 1599,
    discount: "25% OFF",
    image: "sf_tshirt.png",
    images: ["sf_tshirt.png", "sf_tshirt.png", "sf_tshirt.png"],
    description: "Our signature oversized cotton tee offers a relaxed fit with a premium heavyweight feel. Subtle branding makes it a versatile everyday essential.",
    isNewArrival: false,
    salesCount: 450,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 3,
    name: "Navy Formal Shirt",
    category: "Shirt",
    subcategory: "Formal Shirts",
    price: 1299,
    mrp: 1699,
    discount: "24% OFF",
    image: "sf_shirt.png",
    images: ["sf_shirt.png", "sf_shirt.png", "sf_shirt.png"],
    description: "A sharp, tailored formal shirt in a classic navy hue. Wrinkle-resistant fabric ensures you look crisp from morning meetings to evening events.",
    isNewArrival: true,
    salesCount: 120,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 4,
    name: "Beige Cargo Pant",
    category: "Cargo",
    subcategory: "Cargo",
    price: 1399,
    mrp: 1999,
    discount: "30% OFF",
    image: "sf_cargo.png",
    images: ["sf_cargo.png", "sf_cargo.png", "sf_cargo.png"],
    description: "Utility meets style with our beige cargo pants. Featuring deep multi-pockets, reinforced stitching, and a modern straight fit.",
    isNewArrival: false,
    salesCount: 300,
    sizes: ["S", "M", "L", "XL"],
    comingSoon: true
  },
  {
    id: 5,
    name: "Classic White Polo",
    category: "T-shirt",
    subcategory: "Polo T-Shirts",
    price: 899,
    mrp: 1299,
    discount: "31% OFF",
    image: "soulfit_category_tshirt_1777394453783.png",
    images: ["soulfit_category_tshirt_1777394453783.png", "soulfit_category_tshirt_1777394453783.png", "soulfit_category_tshirt_1777394453783.png"],
    description: "The classic white polo shirt, elevated. Crafted from premium pique cotton for superior breathability and a structured collar that holds its shape.",
    isNewArrival: true,
    salesCount: 500,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 6,
    name: "Olive Green Track Pant",
    category: "Pant",
    subcategory: "Track Pants",
    price: 1499,
    mrp: 2199,
    discount: "32% OFF",
    image: "soulfit_straight_pant_1777394417759.png",
    images: ["soulfit_straight_pant_1777394417759.png", "soulfit_straight_pant_1777394417759.png", "soulfit_straight_pant_1777394417759.png"],
    description: "Sleek olive green track pants engineered for movement. Features a tapered fit, adjustable drawstrings, and secure zip pockets.",
    isNewArrival: false,
    salesCount: 80,
    sizes: ["30", "32", "34", "36"]
  },
  {
    id: 7,
    name: "Black Printed Shirt",
    category: "Shirt",
    subcategory: "Printed Shirts",
    price: 1199,
    mrp: 1599,
    discount: "25% OFF",
    image: "soulfit_category_shirt_1777394467745.png",
    images: ["soulfit_category_shirt_1777394467745.png", "soulfit_category_shirt_1777394467745.png", "soulfit_category_shirt_1777394467745.png"],
    description: "Make a statement with this premium black printed shirt. Cut from lightweight, breezy fabric that drapes perfectly for a smart-casual look.",
    isNewArrival: false,
    salesCount: 220,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 8,
    name: "Grey Utility Cargo",
    category: "Cargo",
    subcategory: "Cargo",
    price: 1599,
    mrp: 2299,
    discount: "30% OFF",
    image: "soulfit_category_cargo_1777394485440.png",
    images: ["soulfit_category_cargo_1777394485440.png", "soulfit_category_cargo_1777394485440.png", "soulfit_category_cargo_1777394485440.png"],
    description: "Rugged yet refined grey utility cargos. Designed for durability and functionality without compromising on a sleek, modern aesthetic.",
    isNewArrival: true,
    salesCount: 310,
    sizes: ["30", "32", "34", "36"],
    comingSoon: true
  }
];

