export const products = [
  {
    id: 1,
    name: "Velvet Cloud Sectional",
    category: "Sofa",
    subcategory: "Sectionals",
    price: 89999,
    originalPrice: 124999,
    badge: "Best Seller",
    sizes: ["3-Seater", "5-Seater", "L-Shape"],
    image: "products/velvet_sectional.png",
    images: ["products/velvet_sectional.png"],
    description: "Ultra-plush velvet sectional sofa with high-density foam cushions and solid wood frame. Perfect for modern living spaces.",
    inStock: true,
    isNewArrival: false,
    salesCount: 120
  },
  {
    id: 2,
    name: "Marble Elegance Dining Set",
    category: "Dining",
    subcategory: "Dining Sets",
    price: 145000,
    originalPrice: 180000,
    badge: "New",
    sizes: ["6-Seater", "8-Seater"],
    image: "products/marble_dining_set.png",
    images: ["products/marble_dining_set.png"],
    description: "Handcrafted marble top dining table paired with premium upholstered chairs. A statement piece for your dining room.",
    inStock: true,
    isNewArrival: true,
    salesCount: 45
  },
  {
    id: 3,
    name: "Royal Canopy Bed",
    category: "Bed",
    subcategory: "King Size",
    price: 95000,
    originalPrice: 130000,
    badge: "New",
    sizes: ["Queen", "King"],
    image: "products/royal_canopy_bed.png",
    images: ["products/royal_canopy_bed.png"],
    description: "Majestic canopy bed with intricate wood carvings and a plush headboard. Designed for ultimate comfort and style.",
    inStock: true,
    isNewArrival: true,
    salesCount: 30
  },
  {
    id: 4,
    name: "Aura Crystal Chandelier",
    category: "Lighting",
    subcategory: "Pendants",
    price: 24999,
    originalPrice: 35000,
    badge: "Trending",
    sizes: ["Small", "Large"],
    image: "products/crystal_chandelier.png",
    images: ["products/crystal_chandelier.png"],
    description: "Modern crystal chandelier that creates a stunning visual effect with warm, ambient lighting.",
    inStock: true,
    isNewArrival: false,
    salesCount: 85
  },
  {
    id: 5,
    name: "Scandi Oak Sideboard",
    category: "Storage",
    subcategory: "Cabinets",
    price: 42000,
    originalPrice: 55000,
    badge: "Minimalist",
    sizes: ["4-Drawer", "6-Drawer"],
    image: "products/scandi_oak_sideboard.png",
    images: ["products/scandi_oak_sideboard.png"],
    description: "Clean-lined Scandinavian sideboard crafted from solid oak wood. Minimalist storage for your home.",
    inStock: true,
    isNewArrival: false,
    salesCount: 65
  },
  {
    id: 6,
    name: "Cognac Leather Armchair",
    category: "Sofa",
    subcategory: "Armchairs",
    price: 38000,
    originalPrice: 48000,
    badge: "Classic",
    sizes: ["Standard"],
    image: "products/leather_armchair.png",
    images: ["products/leather_armchair.png"],
    description: "Top-grain cognac leather armchair with a mid-century modern silhouette. Timeless comfort.",
    inStock: true,
    isNewArrival: false,
    salesCount: 90
  }
];
