export const products = [
  {
    id: 1,
    name: "Classic Black Oversized Tee",
    category: "T-shirt",
    subcategory: "T-Shirts",
    price: 999,
    originalPrice: 1499,
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=Black+Tee",
    images: ["https://placehold.co/400x500?text=Black+Tee", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "Premium cotton oversized t-shirt for a relaxed fit and ultimate comfort.",
    inStock: true,
    isNewArrival: false,
    salesCount: 500
  },
  {
    id: 2,
    name: "Pure White Essential Tee",
    category: "T-shirt",
    subcategory: "T-Shirts",
    price: 899,
    originalPrice: 1299,
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=White+Tee",
    images: ["https://placehold.co/400x500?text=White+Tee", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "A must-have white t-shirt crafted from high-quality breathable fabric.",
    inStock: true,
    isNewArrival: true,
    salesCount: 300
  },
  {
    id: 3,
    name: "Midnight Blue Graphic Tee",
    category: "T-shirt",
    subcategory: "T-Shirts",
    price: 1099,
    originalPrice: 1599,
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=Blue+Tee",
    images: ["https://placehold.co/400x500?text=Blue+Tee", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "Stylish graphic t-shirt that adds a pop of personality to your casual look.",
    inStock: true,
    isNewArrival: false,
    salesCount: 450
  },
  {
    id: 4,
    name: "Classic Oxford Shirt",
    category: "Shirt",
    subcategory: "Shirts",
    price: 1499,
    originalPrice: 2199,
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=Oxford+Shirt",
    images: ["https://placehold.co/400x500?text=Oxford+Shirt", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "Sophisticated oxford shirt perfect for both formal and semi-formal occasions.",
    inStock: true,
    isNewArrival: true,
    salesCount: 150
  },
  {
    id: 5,
    name: "Linen Summer Shirt",
    category: "Shirt",
    subcategory: "Shirts",
    price: 1699,
    originalPrice: 2499,
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=Linen+Shirt",
    images: ["https://placehold.co/400x500?text=Linen+Shirt", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "Breathable linen shirt designed to keep you cool and stylish during summer.",
    inStock: true,
    isNewArrival: false,
    salesCount: 280
  },
  {
    id: 6,
    name: "Urban Flannel Shirt",
    category: "Shirt",
    subcategory: "Shirts",
    price: 1399,
    originalPrice: 1999,
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=Flannel+Shirt",
    images: ["https://placehold.co/400x500?text=Flannel+Shirt", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "Classic flannel shirt with a modern twist, perfect for layering.",
    inStock: false,
    isNewArrival: true,
    salesCount: 100
  },
  {
    id: 7,
    name: "Slim Fit Chinos",
    category: "Pant",
    subcategory: "Pants",
    price: 1899,
    originalPrice: 2799,
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=Chinos",
    images: ["https://placehold.co/400x500?text=Chinos", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "Versatile slim-fit chinos that offer a sharp look and comfortable feel.",
    inStock: true,
    isNewArrival: false,
    salesCount: 350
  },
  {
    id: 8,
    name: "Relaxed Fit Lounge Pants",
    category: "Pant",
    subcategory: "Pants",
    price: 1299,
    originalPrice: 1899,
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=Lounge+Pants",
    images: ["https://placehold.co/400x500?text=Lounge+Pants", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "Ultra-comfortable lounge pants for your most relaxed days at home.",
    inStock: true,
    isNewArrival: true,
    salesCount: 220
  },
  {
    id: 9,
    name: "Vintage Denim Jeans",
    category: "Pant",
    subcategory: "Pants",
    price: 2499,
    originalPrice: 3599,
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=Denim+Jeans",
    images: ["https://placehold.co/400x500?text=Denim+Jeans", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "Premium denim jeans with a vintage wash and timeless straight-cut fit.",
    inStock: true,
    isNewArrival: false,
    salesCount: 400
  },
  {
    id: 10,
    name: "Tactical Multi-Pocket Cargo",
    category: "Cargo",
    subcategory: "Cargos",
    price: 2199,
    originalPrice: 3199,
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=Tactical+Cargo",
    images: ["https://placehold.co/400x500?text=Tactical+Cargo", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "Functional cargo pants with multiple pockets for a rugged, urban look.",
    inStock: true,
    isNewArrival: true,
    salesCount: 180
  },
  {
    id: 11,
    name: "Sandstone Utility Cargo",
    category: "Cargo",
    subcategory: "Cargos",
    price: 1999,
    originalPrice: 2899,
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=Utility+Cargo",
    images: ["https://placehold.co/400x500?text=Utility+Cargo", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "Durable utility cargos in a versatile sandstone shade for everyday wear.",
    inStock: true,
    isNewArrival: false,
    salesCount: 320
  },
  {
    id: 12,
    name: "Stealth Black Cargo",
    category: "Cargo",
    subcategory: "Cargos",
    price: 2299,
    originalPrice: 3399,
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://placehold.co/400x500?text=Black+Cargo",
    images: ["https://placehold.co/400x500?text=Black+Cargo", "https://placehold.co/400x500?text=Detail+1", "https://placehold.co/400x500?text=Detail+2"],
    description: "Sleek and modern black cargo pants for a sharp, tactical aesthetic.",
    inStock: true,
    isNewArrival: true,
    salesCount: 250
  }
];


